version: "3.4"
services:
  inferno:
    network_mode: host
    build: .
    # (optional) Volume mount your locally stored inferno-os repo
    #volumes:
    #  - ${INFERNO_ROOT}:/proj/inferno-os
    environment:
      - DISPLAY=${DISPLAY}  
    stdin_open: true
    tty: true
    labels:
        inferno.name: "inferno_docker_inferno_1"
